name: OpenAI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get diff from PR
        id: diff
        run: |
          git fetch origin main --depth=1
          git diff origin/main...HEAD > pr_diff.txt
          echo "DIFF<<EOF" >> $GITHUB_ENV
          cat pr_diff.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Call OpenAI API
        id: openai
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          BODY=$(jq -n --arg diff "${{ env.DIFF }}" '{
            model: "gpt-3.5-turbo",
            messages: [
              {
                role: "system",
                content: "You are a strict code reviewer. Review this code diff. \
Each Python function should have a docstring that completes the sentence: \
\"This function will ...\". If all is good, reply with PASS. Otherwise, suggest improvements."
              },
              {
                role: "user",
                content: $diff
              }
            ]
          }')

          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "$BODY")

          echo "$RESPONSE" > response.json

          SUGGESTIONS=$(jq -r '.choices[0].message.content' response.json)

          # Save for comment step
          echo "SUGGESTIONS<<EOF" >> $GITHUB_ENV
          echo "$SUGGESTIONS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🤖 **OpenAI Review Results:**
            ```
            ${{ env.SUGGESTIONS }}
            ```
